"""
zenflow.migrate
────────────────
Schema migrations with Alembic (Phase 12.2.3, ADR-45).

    python -m zenflow.migrate current          # the database's revision
    python -m zenflow.migrate upgrade          # apply every pending revision
    python -m zenflow.migrate check            # fail if zenflow.schema has changes with no revision
    python -m zenflow.migrate revision "add x" # a new revision, autogenerated from zenflow.schema

**How a database comes under Alembic.** `0001_baseline` is exactly the schema the app built with raw
SQL before Alembic (`tests/integration/test_schema_baseline.py`). An existing database — built by
`bot.db.init_db()` — is therefore *stamped* 0001 (nothing runs), then upgraded. `init_db()` does
this on every start, cheaply: it only touches Alembic when the stored revision is not the head.

**Changing the schema from now on:** edit `zenflow/schema.py`, run `python -m zenflow.migrate
revision "…"`, review the generated file under `migrations/versions/`. Never add to the legacy
`ALTER TABLE` list in `bot/db.py` — a test keeps it frozen.
"""

from __future__ import annotations

import argparse
import re
import sqlite3
import sys
from functools import lru_cache
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ALEMBIC_INI = ROOT / "alembic.ini"
BASELINE = "0001"


def database_url() -> str:
    """The SQLAlchemy URL of the app's database (SQLite file today; ZF_DB_URL arrives in 12.2.2)."""
    from bot.db import db_path

    return f"sqlite:///{db_path()}"


#: Postgres reflects every literal with its type: 'x'::text, timezone('UTC'::text, now())
_PG_CAST = re.compile(r"::(?:character varying|double precision|[a-z_][a-z0-9_]*)")


def _norm_default(value: object) -> str | None:
    """`(datetime('now'))`, `'x'`, `''`, `'x'::text` → comparable text: outer parens, quotes and
    Postgres casts do not matter; anything else (a different value, a different function) does."""
    if value is None:
        return None
    text = _PG_CAST.sub("", str(getattr(value, "text", value))).strip()
    while text.startswith("(") and text.endswith(")"):
        text = text[1:-1].strip()
    return text.strip("'\"")


def compare_default(  # type: ignore[no-untyped-def]
    context, inspected_column, metadata_column, inspected, metadata_default, rendered
):
    """True only for a real default change (SQLite reflects '' and quoted literals unevenly)."""
    return _norm_default(inspected) != _norm_default(rendered)


def _config(url: str | None = None):  # type: ignore[no-untyped-def]
    from alembic.config import Config

    cfg = Config(str(ALEMBIC_INI))
    cfg.set_main_option("script_location", str(ROOT / "migrations"))
    if url:
        cfg.set_main_option("sqlalchemy.url", url)
    return cfg


@lru_cache(maxsize=1)
def head() -> str:
    """The newest revision in migrations/versions (read once per process)."""
    from alembic.script import ScriptDirectory

    revision = ScriptDirectory.from_config(_config()).get_current_head()
    if revision is None:
        raise RuntimeError("migrations/versions has no revision")
    return revision


def current(conn: sqlite3.Connection) -> str | None:
    """The revision a SQLite database is at, or None when Alembic has never seen it."""
    has_table = conn.execute(
        "SELECT 1 FROM sqlite_master WHERE type='table' AND name='alembic_version'"
    ).fetchone()
    if not has_table:
        return None
    row = conn.execute("SELECT version_num FROM alembic_version").fetchone()
    return str(row[0]) if row else None


def _stamp_baseline(conn: sqlite3.Connection) -> None:
    conn.execute("""CREATE TABLE IF NOT EXISTS alembic_version (
               version_num VARCHAR(32) NOT NULL,
               CONSTRAINT alembic_version_pkc PRIMARY KEY (version_num))""")
    conn.execute("DELETE FROM alembic_version")
    conn.execute("INSERT INTO alembic_version (version_num) VALUES (?)", (BASELINE,))


def ensure_sqlite(conn: sqlite3.Connection) -> None:
    """Bring the app's SQLite database under Alembic and up to the head revision.

    Called by `bot.db.init_db()` after the legacy statements have built (or verified) the
    baseline schema, so a database Alembic has never seen is stamped 0001 — never re-created.
    """
    if current(conn) is None:
        _stamp_baseline(conn)
    if current(conn) != head():
        upgrade()


def upgrade(url: str | None = None, revision: str = "head") -> None:
    from alembic import command

    command.upgrade(_config(url or database_url()), revision)


def main(argv: list[str] | None = None) -> int:
    from alembic import command

    parser = argparse.ArgumentParser(description="Schema migrations (Alembic, Phase 12.2.3).")
    parser.add_argument("--url", help="SQLAlchemy URL (default: the app's database)")
    sub = parser.add_subparsers(dest="cmd", required=True)
    sub.add_parser("current", help="show the database's revision")
    up = sub.add_parser("upgrade", help="apply pending revisions")
    up.add_argument("revision", nargs="?", default="head")
    st = sub.add_parser("stamp", help="mark the database as being at a revision (runs nothing)")
    st.add_argument("revision")
    sub.add_parser("check", help="fail if zenflow.schema has changes no revision covers")
    rev = sub.add_parser("revision", help="autogenerate a new revision from zenflow.schema")
    rev.add_argument("message")
    args = parser.parse_args(argv)

    cfg = _config(args.url or database_url())
    if args.cmd == "current":
        command.current(cfg, verbose=False)
    elif args.cmd == "upgrade":
        command.upgrade(cfg, args.revision)
    elif args.cmd == "stamp":
        command.stamp(cfg, args.revision)
    elif args.cmd == "check":
        command.check(cfg)
    else:
        command.revision(cfg, message=args.message, autogenerate=True)
    return 0


if __name__ == "__main__":
    sys.exit(main())
