"""baseline — the schema exactly as the app built it with raw SQL before Alembic (Phase 12.2.3)

Revision ID: 0001
Revises:
Create Date: 2026-10-02

Generated from zenflow.schema and then frozen: later schema changes are NEW revisions, never edits
here. An existing database is stamped at this revision (nothing runs); an empty one — SQLite or
Postgres — is built by it. `tests/integration/test_schema_baseline.py` proves it equals the legacy
schema on SQLite; CI's `postgres` job builds it on Postgres.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def _utc_now() -> sa.TextClause:
    """The legacy `datetime('now')` default ('YYYY-MM-DD HH:MM:SS', UTC) of the oldest columns."""
    if op.get_context().dialect.name == "postgresql":
        return sa.text("(to_char(timezone('UTC', now()), 'YYYY-MM-DD HH24:MI:SS'))")
    return sa.text("(datetime('now'))")


PATIENT_CONTACTS_VIEW = """CREATE VIEW patient_contacts AS
SELECT pc.patient_id, pc.channel, pc.external_id
FROM patient_channels pc
WHERE pc.id = (
    SELECT c2.id FROM patient_channels c2
    WHERE c2.patient_id = pc.patient_id
    ORDER BY c2.is_primary DESC, c2.id DESC
    LIMIT 1
)"""

AUDIT_GUARD = {
    "sqlite": (
        """CREATE TRIGGER audit_log_is_append_only_update
       BEFORE UPDATE ON audit_log
       BEGIN SELECT RAISE(ABORT, 'audit_log is append-only'); END""",
        """CREATE TRIGGER audit_log_is_append_only_delete
       BEFORE DELETE ON audit_log
       BEGIN SELECT RAISE(ABORT, 'audit_log is append-only'); END""",
    ),
    "postgresql": (
        """CREATE FUNCTION audit_log_append_only() RETURNS trigger AS $$
       BEGIN RAISE EXCEPTION 'audit_log is append-only'; END
       $$ LANGUAGE plpgsql""",
        """CREATE TRIGGER audit_log_is_append_only_update BEFORE UPDATE ON audit_log
       FOR EACH ROW EXECUTE FUNCTION audit_log_append_only()""",
        """CREATE TRIGGER audit_log_is_append_only_delete BEFORE DELETE ON audit_log
       FOR EACH ROW EXECUTE FUNCTION audit_log_append_only()""",
    ),
}


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "acupoints",
        sa.Column("code", sa.Text(), nullable=False),
        sa.Column("aliases", sa.Text(), server_default="[]", nullable=False),
        sa.Column("name_pinyin", sa.Text(), server_default="", nullable=False),
        sa.Column("name_cn", sa.Text(), server_default="", nullable=False),
        sa.Column("name_en", sa.Text(), server_default="", nullable=False),
        sa.Column("channel", sa.Text(), server_default="", nullable=False),
        sa.Column("location", sa.Text(), server_default="", nullable=False),
        sa.Column("actions", sa.Text(), server_default="", nullable=False),
        sa.Column("needle_depth", sa.Text(), server_default="", nullable=False),
        sa.Column("needle_angle", sa.Text(), server_default="", nullable=False),
        sa.Column("contraindications", sa.Text(), server_default="[]", nullable=False),
        sa.Column("translations", sa.Text(), server_default="{}", nullable=False),
        sa.Column("source", sa.Text(), server_default="", nullable=False),
        sa.Column("licence", sa.Text(), server_default="", nullable=False),
        sa.Column("updated_at", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("code"),
    )
    op.create_table(
        "ai_calls",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ts", sa.Text(), nullable=False),
        sa.Column("appointment_id", sa.Integer(), nullable=True),
        sa.Column("stage", sa.Text(), nullable=False),
        sa.Column("provider", sa.Text(), server_default="", nullable=False),
        sa.Column("model", sa.Text(), server_default="", nullable=False),
        sa.Column("prompt_tokens", sa.Integer(), nullable=True),
        sa.Column("completion_tokens", sa.Integer(), nullable=True),
        sa.Column("duration_ms", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("prompt_sha256", sa.Text(), server_default="", nullable=False),
        sa.Column("response_sha256", sa.Text(), nullable=True),
        sa.Column("prompt_debug", sa.Text(), nullable=True),
        sa.Column("response_debug", sa.Text(), nullable=True),
        sa.CheckConstraint("status IN ('ok','error','timeout')"),
        sa.PrimaryKeyConstraint("id"),
        sqlite_autoincrement=True,
    )
    with op.batch_alter_table("ai_calls", schema=None) as batch_op:
        batch_op.create_index("idx_ai_calls_appointment", ["appointment_id", "id"], unique=False)
        batch_op.create_index("idx_ai_calls_stage", ["stage", "ts"], unique=False)
        batch_op.create_index("idx_ai_calls_ts", ["ts"], unique=False)

    op.create_table(
        "api_clients",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("key_hash", sa.Text(), nullable=False),
        sa.Column("created_at", sa.Text(), nullable=False),
        sa.Column("last_used_at", sa.Text(), nullable=True),
        sa.Column("revoked_at", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("key_hash"),
        sa.UniqueConstraint("name"),
        sqlite_autoincrement=True,
    )
    op.create_table(
        "api_idempotency",
        sa.Column("client", sa.Text(), nullable=False),
        sa.Column("key", sa.Text(), nullable=False),
        sa.Column("request_hash", sa.Text(), nullable=False),
        sa.Column("status_code", sa.Integer(), nullable=True),
        sa.Column("response_json", sa.Text(), nullable=True),
        sa.Column("created_at", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("client", "key"),
    )
    op.create_table(
        "appointments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("patient_id", sa.Integer(), nullable=False),
        sa.Column("patient_name", sa.Text(), nullable=False),
        sa.Column("therapist_id", sa.Text(), nullable=False),
        sa.Column("date", sa.Text(), nullable=False),
        sa.Column("time", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), server_default="active", nullable=True),
        sa.Column("gcal_apt_event_id", sa.Text(), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("created_at", sa.Text(), server_default=_utc_now(), nullable=True),
        sa.Column("source", sa.Text(), server_default="telegram", nullable=True),
        sa.Column("patient_phone", sa.Text(), nullable=True),
        sa.Column("patient_email", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sqlite_autoincrement=True,
    )
    with op.batch_alter_table("appointments", schema=None) as batch_op:
        batch_op.create_index(
            "ux_appointments_active_slot",
            ["therapist_id", "date", "time"],
            unique=True,
            sqlite_where=sa.text("status='active'"),
            postgresql_where=sa.text("status='active'"),
        )

    op.create_table(
        "audit_log",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ts", sa.Text(), nullable=False),
        sa.Column("actor_type", sa.Text(), nullable=False),
        sa.Column("actor_id", sa.Text(), server_default="", nullable=False),
        sa.Column("action", sa.Text(), nullable=False),
        sa.Column("entity_type", sa.Text(), nullable=False),
        sa.Column("entity_id", sa.Text(), nullable=False),
        sa.Column("before_json", sa.Text(), nullable=True),
        sa.Column("after_json", sa.Text(), nullable=True),
        sa.Column("ip", sa.Text(), nullable=True),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.Column("request_id", sa.Text(), nullable=True),
        sa.CheckConstraint("actor_type IN ('therapist','patient','system','ai','api')"),
        sa.PrimaryKeyConstraint("id"),
        sqlite_autoincrement=True,
    )
    with op.batch_alter_table("audit_log", schema=None) as batch_op:
        batch_op.create_index("idx_audit_actor", ["actor_type", "actor_id", "id"], unique=False)
        batch_op.create_index("idx_audit_entity", ["entity_type", "entity_id", "id"], unique=False)
        batch_op.create_index("idx_audit_ts", ["ts"], unique=False)

    op.create_table(
        "availability",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("therapist_id", sa.Text(), nullable=False),
        sa.Column("start_dt", sa.Text(), nullable=False),
        sa.Column("end_dt", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "bot_persistence",
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("key", sa.Text(), nullable=False),
        sa.Column("value_json", sa.Text(), nullable=False),
        sa.Column("updated_at", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("kind", "name", "key"),
    )
    op.create_table(
        "google_tokens",
        sa.Column("therapist_id", sa.Text(), nullable=False),
        sa.Column("encrypted_token", sa.Text(), nullable=False),
        sa.Column("scopes", sa.Text(), nullable=True),
        sa.Column("updated_at", sa.Text(), server_default=_utc_now(), nullable=True),
        sa.PrimaryKeyConstraint("therapist_id"),
    )
    op.create_table(
        "intake_sessions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("appointment_id", sa.Integer(), nullable=False),
        sa.Column("patient_id", sa.Integer(), nullable=False),
        sa.Column("therapist_id", sa.Text(), nullable=False),
        sa.Column("history_json", sa.Text(), nullable=True),
        sa.Column("created_at", sa.Text(), server_default=_utc_now(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sqlite_autoincrement=True,
    )
    op.create_table(
        "jobs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("payload_json", sa.Text(), server_default="{}", nullable=False),
        sa.Column("run_at", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), server_default="pending", nullable=False),
        sa.Column("attempts", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("max_attempts", sa.Integer(), server_default=sa.text("5"), nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("idempotency_key", sa.Text(), nullable=True),
        sa.Column("locked_by", sa.Text(), nullable=True),
        sa.Column("locked_at", sa.Text(), nullable=True),
        sa.Column("created_at", sa.Text(), nullable=False),
        sa.Column("updated_at", sa.Text(), nullable=False),
        sa.Column("completed_at", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("idempotency_key"),
        sqlite_autoincrement=True,
    )
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.create_index("idx_jobs_claim", ["status", "run_at"], unique=False)

    op.create_table(
        "leases",
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("holder", sa.Text(), nullable=False),
        sa.Column("expires_at", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("name"),
    )
    op.create_table(
        "message_log",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ts", sa.Text(), nullable=False),
        sa.Column("direction", sa.Text(), server_default="out", nullable=False),
        sa.Column("channel", sa.Text(), nullable=False),
        sa.Column("patient_id", sa.Integer(), nullable=True),
        sa.Column("therapist_id", sa.Text(), server_default="", nullable=False),
        sa.Column("appointment_id", sa.Integer(), nullable=True),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("provider_message_id", sa.Text(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.CheckConstraint("channel IN ('telegram','whatsapp','email')"),
        sa.CheckConstraint("direction IN ('out','in')"),
        sa.CheckConstraint("kind IN ('recommendations','followup','confirmation','relay')"),
        sa.CheckConstraint("status IN ('sent','failed')"),
        sa.PrimaryKeyConstraint("id"),
        sqlite_autoincrement=True,
    )
    with op.batch_alter_table("message_log", schema=None) as batch_op:
        batch_op.create_index("idx_message_log_appointment", ["appointment_id", "ts"], unique=False)

    op.create_table(
        "notifications",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("therapist_id", sa.Text(), nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("severity", sa.Text(), server_default="info", nullable=True),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("body", sa.Text(), nullable=True),
        sa.Column("appointment_id", sa.Integer(), nullable=True),
        sa.Column("patient_id", sa.Integer(), nullable=True),
        sa.Column("patient_name", sa.Text(), nullable=True),
        sa.Column("persistent", sa.Integer(), server_default=sa.text("0"), nullable=True),
        sa.Column("read_at", sa.Text(), nullable=True),
        sa.Column("resolved_at", sa.Text(), nullable=True),
        sa.Column("created_at", sa.Text(), server_default=_utc_now(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sqlite_autoincrement=True,
    )
    with op.batch_alter_table("notifications", schema=None) as batch_op:
        batch_op.create_index(
            "idx_notif_therapist_unread", ["therapist_id", "read_at"], unique=False
        )

    op.create_table(
        "patients",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("full_name", sa.Text(), server_default="", nullable=False),
        sa.Column("phone", sa.Text(), nullable=True),
        sa.Column("email", sa.Text(), nullable=True),
        sa.Column("lang", sa.Text(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("legacy_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.Text(), nullable=False),
        sa.Column("updated_at", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("legacy_id"),
        sqlite_autoincrement=True,
    )
    op.create_table(
        "revoked_sessions",
        sa.Column("sid", sa.Text(), nullable=False),
        sa.Column("revoked_at", sa.Text(), nullable=False),
        sa.Column("expires_at", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("sid"),
    )
    with op.batch_alter_table("revoked_sessions", schema=None) as batch_op:
        batch_op.create_index("idx_revoked_sessions_expiry", ["expires_at"], unique=False)

    op.create_table(
        "schema_migrations",
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("applied_at", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("name"),
    )
    op.create_table(
        "therapists",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("telegram_id", sa.Integer(), server_default=sa.text("0"), nullable=True),
        sa.Column("email", sa.Text(), nullable=True),
        sa.Column("password_hash", sa.Text(), nullable=True),
        sa.Column("google_id", sa.Text(), nullable=True),
        sa.Column("calendar_name", sa.Text(), server_default="ZenFlow Availability", nullable=True),
        sa.Column("active", sa.Integer(), server_default=sa.text("0"), nullable=True),
        sa.Column("created_at", sa.Text(), server_default=_utc_now(), nullable=True),
        sa.Column("language", sa.Text(), server_default="en", nullable=True),
        sa.Column("ui_prefs", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "treatment_notes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("appointment_id", sa.Integer(), nullable=False),
        sa.Column("patient_id", sa.Integer(), nullable=False),
        sa.Column("tcm_pattern", sa.Text(), nullable=True),
        sa.Column("treatment_principles", sa.Text(), nullable=True),
        sa.Column("diagnosis_certainty", sa.Integer(), server_default=sa.text("0"), nullable=True),
        sa.Column("ai_suggested_points", sa.Text(), nullable=True),
        sa.Column("ai_recommendations", sa.Text(), nullable=True),
        sa.Column("tongue_observation", sa.Text(), nullable=True),
        sa.Column("pulse_observation", sa.Text(), nullable=True),
        sa.Column("session_notes", sa.Text(), nullable=True),
        sa.Column("used_points", sa.Text(), nullable=True),
        sa.Column("recommendations_sent_at", sa.Text(), nullable=True),
        sa.Column("created_at", sa.Text(), server_default=_utc_now(), nullable=True),
        sa.Column("updated_at", sa.Text(), server_default=_utc_now(), nullable=True),
        sa.Column("completed_at", sa.Text(), nullable=True),
        sa.Column("followup_rating", sa.Integer(), nullable=True),
        sa.Column("followup_sent_at", sa.Text(), nullable=True),
        sa.Column("therapist_diagnosis", sa.Text(), nullable=True),
        sa.Column("therapist_notes", sa.Text(), nullable=True),
        sa.Column("manual_feedback_rating", sa.Integer(), nullable=True),
        sa.Column("manual_feedback_notes", sa.Text(), nullable=True),
        sa.Column("followup_conversation", sa.Text(), nullable=True),
        sa.Column("pending_recommendations", sa.Text(), nullable=True),
        sa.Column("pending_rec_send_at", sa.Text(), nullable=True),
        sa.Column("points_status", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("appointment_id"),
        sqlite_autoincrement=True,
    )
    op.create_table(
        "acupoint_images",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("point_code", sa.Text(), nullable=False),
        sa.Column("storage_key", sa.Text(), nullable=False),
        sa.Column("thumb_key", sa.Text(), nullable=False),
        sa.Column("kind", sa.Text(), server_default="diagram", nullable=False),
        sa.Column("width", sa.Integer(), nullable=False),
        sa.Column("height", sa.Integer(), nullable=False),
        sa.Column("sha256", sa.Text(), nullable=False),
        sa.Column("original_name", sa.Text(), server_default="", nullable=False),
        sa.Column("credit", sa.Text(), nullable=False),
        sa.Column("licence", sa.Text(), nullable=False),
        sa.Column("licence_url", sa.Text(), server_default="", nullable=False),
        sa.Column("source_url", sa.Text(), server_default="", nullable=False),
        sa.Column("is_primary", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("created_at", sa.Text(), nullable=False),
        sa.Column("updated_at", sa.Text(), nullable=False),
        sa.CheckConstraint("kind IN ('diagram', 'photo', '3d')"),
        sa.ForeignKeyConstraint(["point_code"], ["acupoints.code"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("storage_key"),
        sqlite_autoincrement=True,
    )
    with op.batch_alter_table("acupoint_images", schema=None) as batch_op:
        batch_op.create_index("idx_acupoint_images_code", ["point_code"], unique=False)

    op.create_table(
        "followups",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("appointment_id", sa.Integer(), nullable=False),
        sa.Column("patient_id", sa.Integer(), nullable=False),
        sa.Column("therapist_id", sa.Text(), server_default="", nullable=False),
        sa.Column("channel", sa.Text(), server_default="telegram", nullable=False),
        sa.Column("status", sa.Text(), server_default="scheduled", nullable=False),
        sa.Column("auto", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("scheduled_for", sa.Text(), nullable=True),
        sa.Column("sent_at", sa.Text(), nullable=True),
        sa.Column("completed_at", sa.Text(), nullable=True),
        sa.Column("step", sa.Integer(), nullable=True),
        sa.Column("pain_level", sa.Integer(), nullable=True),
        sa.Column("improvement_rating", sa.Integer(), nullable=True),
        sa.Column("side_effects", sa.Text(), nullable=True),
        sa.Column("sleep_quality", sa.Text(), nullable=True),
        sa.Column("adherence", sa.Text(), nullable=True),
        sa.Column("free_text", sa.Text(), nullable=True),
        sa.Column("ai_summary", sa.Text(), nullable=True),
        sa.Column("needs_attention", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("conversation_json", sa.Text(), nullable=True),
        sa.Column("source", sa.Text(), server_default="patient", nullable=False),
        sa.Column("created_at", sa.Text(), nullable=False),
        sa.Column("updated_at", sa.Text(), nullable=False),
        sa.CheckConstraint("adherence IN ('yes','partly','no')"),
        sa.CheckConstraint("sleep_quality IN ('worse','same','better')"),
        sa.CheckConstraint("source IN ('patient','therapist_manual')"),
        sa.CheckConstraint(
            "status IN ('scheduled','sent','in_progress','completed','expired','no_channel')"
        ),
        sa.CheckConstraint("improvement_rating BETWEEN 1 AND 5"),
        sa.CheckConstraint("pain_level BETWEEN 0 AND 10"),
        sa.ForeignKeyConstraint(["appointment_id"], ["appointments.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("appointment_id"),
        sqlite_autoincrement=True,
    )
    with op.batch_alter_table("followups", schema=None) as batch_op:
        batch_op.create_index(
            "idx_followups_patient_status", ["patient_id", "status"], unique=False
        )
        batch_op.create_index("idx_followups_status_sent", ["status", "sent_at"], unique=False)

    op.create_table(
        "patient_channels",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("patient_id", sa.Integer(), nullable=False),
        sa.Column("channel", sa.Text(), nullable=False),
        sa.Column("external_id", sa.Text(), nullable=False),
        sa.Column("is_primary", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("verified_at", sa.Text(), nullable=True),
        sa.Column("created_at", sa.Text(), nullable=False),
        sa.CheckConstraint("channel IN ('telegram','whatsapp')"),
        sa.CheckConstraint("is_primary IN (0, 1)"),
        sa.CheckConstraint("length(external_id) BETWEEN 1 AND 64"),
        sa.ForeignKeyConstraint(["patient_id"], ["patients.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("channel", "external_id"),
        sqlite_autoincrement=True,
    )
    with op.batch_alter_table("patient_channels", schema=None) as batch_op:
        batch_op.create_index("idx_patient_channels_patient", ["patient_id"], unique=False)

    # ### end Alembic commands ###
    op.execute(PATIENT_CONTACTS_VIEW)
    for statement in AUDIT_GUARD[op.get_context().dialect.name]:
        op.execute(statement)


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP VIEW IF EXISTS patient_contacts")
    op.execute(
        "DROP TRIGGER IF EXISTS audit_log_is_append_only_update"
        + (" ON audit_log" if op.get_context().dialect.name == "postgresql" else "")
    )
    op.execute(
        "DROP TRIGGER IF EXISTS audit_log_is_append_only_delete"
        + (" ON audit_log" if op.get_context().dialect.name == "postgresql" else "")
    )
    if op.get_context().dialect.name == "postgresql":
        op.execute("DROP FUNCTION IF EXISTS audit_log_append_only()")
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("patient_channels", schema=None) as batch_op:
        batch_op.drop_index("idx_patient_channels_patient")

    op.drop_table("patient_channels")
    with op.batch_alter_table("followups", schema=None) as batch_op:
        batch_op.drop_index("idx_followups_status_sent")
        batch_op.drop_index("idx_followups_patient_status")

    op.drop_table("followups")
    with op.batch_alter_table("acupoint_images", schema=None) as batch_op:
        batch_op.drop_index("idx_acupoint_images_code")

    op.drop_table("acupoint_images")
    op.drop_table("treatment_notes")
    op.drop_table("therapists")
    op.drop_table("schema_migrations")
    with op.batch_alter_table("revoked_sessions", schema=None) as batch_op:
        batch_op.drop_index("idx_revoked_sessions_expiry")

    op.drop_table("revoked_sessions")
    op.drop_table("patients")
    with op.batch_alter_table("notifications", schema=None) as batch_op:
        batch_op.drop_index("idx_notif_therapist_unread")

    op.drop_table("notifications")
    with op.batch_alter_table("message_log", schema=None) as batch_op:
        batch_op.drop_index("idx_message_log_appointment")

    op.drop_table("message_log")
    op.drop_table("leases")
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.drop_index("idx_jobs_claim")

    op.drop_table("jobs")
    op.drop_table("intake_sessions")
    op.drop_table("google_tokens")
    op.drop_table("bot_persistence")
    op.drop_table("availability")
    with op.batch_alter_table("audit_log", schema=None) as batch_op:
        batch_op.drop_index("idx_audit_ts")
        batch_op.drop_index("idx_audit_entity")
        batch_op.drop_index("idx_audit_actor")

    op.drop_table("audit_log")
    with op.batch_alter_table("appointments", schema=None) as batch_op:
        batch_op.drop_index(
            "ux_appointments_active_slot",
            sqlite_where=sa.text("status='active'"),
            postgresql_where=sa.text("status='active'"),
        )

    op.drop_table("appointments")
    op.drop_table("api_idempotency")
    op.drop_table("api_clients")
    with op.batch_alter_table("ai_calls", schema=None) as batch_op:
        batch_op.drop_index("idx_ai_calls_ts")
        batch_op.drop_index("idx_ai_calls_stage")
        batch_op.drop_index("idx_ai_calls_appointment")

    op.drop_table("ai_calls")
    op.drop_table("acupoints")
    # ### end Alembic commands ###
